### ISSUE TITLE
找到一个bug

### ISSUE THREAD

**Issue by zxdstyle** [SmallRuralDog/laravel-vue-admin#1]
执行这个命令的时候没有发布数据库迁移文件
```
php artisan vendor:publish --provider="SmallRuralDog\Admin\AdminServiceProvider"
```

导致执行`php artisan admin:install`的时候找不到表

**Comment by zxdstyle** [comment]
![image](https://user-images.githubusercontent.com/38398954/72768652-0dc16c00-3c33-11ea-8afa-65eadbcb7b8b.png)
首页报错

**Comment by zxdstyle** [comment]
![image](https://user-images.githubusercontent.com/38398954/72768692-35183900-3c33-11ea-92e0-6505c23b5e30.png)
字体文件引入路径错误

**Comment by zxdstyle** [comment]
任重道远啊 兄嘚加油

**Comment by SmallRuralDog** [comment]
@zxdstyle 非常感谢！！
