### ISSUE TITLE
Upload 上传普通文件提示 "The file must be an image."

### ISSUE THREAD

**Issue by anjestar** [SmallRuralDog/laravel-vue-admin#13]
问题：Upload 上传普通文件提示 "The file must be an image."
代码：Upload::make()->file()

**Comment by hedeqiang** [comment]
请问下 这个 pr 为什么关闭？ 现在图片是无法上传的？ 只能以 `file()` 的形式上传，使用 `image()` 或者 `avatar()` 会提示`The file must be an image."`
