### ISSUE TITLE
安装完毕访问提示404

### ISSUE THREAD

**Issue by ManiuLtd** [SmallRuralDog/laravel-vue-admin#17]
按照说明文档中的安装部分，安装完后数据库表都正常创建了，
但是按说明的访问我的http://vue-admin.test/admin
提示404，请教下是啥原因啊
这个基于vue的话如果有增加页面/组件之类的需要build吗？具体怎么操作呢？

**Comment by SmallRuralDog** [comment]
可以打印一下路由列表，看下路由是否存在

**Comment by SmallRuralDog** [comment]
如果是系统内置的组件不用build，自定义组件需要创建扩展，具体可以查看文档
