### ISSUE TITLE
Cascader数据量稍微大点就很卡

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#19]
我的地区表用Cascader级联，数据量在4000左右，耗时需要10秒左右，而且取数据我用了缓存的，代码如下：
`$form->item('area_id', '所在地')->displayComponent(function () {
            $cacheName = 'area_all_node';
            $allNodes = Cache::get($cacheName);
            if (!$allNodes) {
                $areas = new Area();
                $allNodes = $areas->buildNestedArray([], 100000);
            }
            return Cascader::make()->options($allNodes)->value('id')->label('name')->expandTrigger('hover')->emitPath(false);
        });`

我估计这里面渲染有很大问题，麻烦看看。

**Comment by SmallRuralDog** [comment]
可以用异步加载

**Comment by ChartWay** [comment]
搞定。感谢。代码：
`return Cascader::make()->lazy(true, route('admin.areas.getAreas'))->value('id')->label('name')->emitPath(false);`

PHP代码：
`public function getAreas()
    {
        $params = \request('params');
        $parent_id = 100000;
        if ($params) {
            $parent_id = $params['id'];
        }
        $areas = Area::where('parent_id', $parent_id)->get();
        return ['data' => $areas];
    }`

注意，是post请求！！！没办法，框架写死的，将就着。
