### ISSUE TITLE
建议增加隐藏操作列方法

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#21]
目前有隐藏操作方法的方法，但是有时候需要整个操作列隐藏，希望增加该方法。

**Comment by SmallRuralDog** [comment]
```
$actions->hideActions();
```

**Comment by ChartWay** [comment]
> ```
> $actions->hideActions();
> ```

不对啊，我用这个方法并不能隐藏列，是表格的列哦，不是操作按钮。这个方法只是隐藏了所有操作按钮，但是操作列还在，只不过空列了。代码：

`$grid->actions(function (Grid\Actions $actions) {
            $actions->hideActions();
        })->toolbars(function (Grid\Toolbars $toolbars) {
            $toolbars->hideCreateButton();
        });`
