### ISSUE TITLE
建议对按钮增加权限控制

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#26]
目前的权限控制局限于菜单和接口层面，在实际开发中很多需要对按钮进行控制，比如用户删除按钮，没有权限就可以让按钮置灰或者隐藏，而不是点击后提示没有权限。建议可以在actions上增加permission属性来控制权限，另外permissions用户登陆后保存在localstorage去，不用每次去后端校验。

**Comment by SmallRuralDog** [comment]
可以在PHP代码里面判断权限然后设置组件属性
