### ISSUE TITLE
菜单栏太长显示不全

### ISSUE THREAD

**Issue by fansweige** [SmallRuralDog/laravel-vue-admin#38]
当菜单名称配置太长时显示不全， 建议左侧菜单可拖拽，或者 鼠标悬停显示全部信息

<img width="256" alt="图片" src="https://user-images.githubusercontent.com/15138052/86422711-6f245580-bd10-11ea-963d-da2b3547c3db.png">

**Comment by anyuzhe** [comment]
菜单名称取短点不就行了  菜单的名称名字这么长看着也累啊
