### ISSUE TITLE
自定义组件的required()属性识别不了

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#40]
目前测试了几个是识别不了的 CSwitch、RadioGroup、CheckBox，不知道其他的怎么样，例如：
`$form->item('gender', '性别')->required()->component(RadioGroup::make(1, [
            Radio::make(1, '男'),
            Radio::make(2, '女'),
            Radio::make(0, '保密')
        ]));`

![image](https://user-images.githubusercontent.com/44427400/86516662-232ef900-be55-11ea-8194-25094fd9885a.png)

**Comment by SmallRuralDog** [comment]
`required()`默认是string类型，其他类型需要指定，如`required('array')`
