### ISSUE TITLE
建议$http的get()方法支持入参

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#54]
建议改为get(uri,param={})，当param参数为空时，uri不变，当param有信息时，将参数附加至uri，这样可以大大简化前端拼接的麻烦。

**Comment by SmallRuralDog** [comment]
能具体说一下场景吗

**Comment by ChartWay** [comment]
> 能具体说一下场景吗

比如 /article/edit?keyword=abc&sort=id&publish_date=2020-09-10这种，如果使用URL拼接，意味着需要拼很多参数，那为什么不用多支持get('/article/edit',param={keyword:'abc',sort:'id',publish_date:'2020-09-10'})这种模式入参呢，然后系统做转换

**Comment by SmallRuralDog** [comment]
你可以这样
```js
this.$http.get('/user', {
    params: {
      ID: 12345
    }
  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
```
