### ISSUE TITLE
多对多模型写入报错 

### ISSUE THREAD

**Issue by ChartWay** [SmallRuralDog/laravel-vue-admin#57]
![image](https://user-images.githubusercontent.com/44427400/89964145-f05df900-dc7b-11ea-8ccd-d85afad3ec97.png)
![image](https://user-images.githubusercontent.com/44427400/89964154-f522ad00-dc7b-11ea-8f46-048977c5bcc2.png)
![image](https://user-images.githubusercontent.com/44427400/89964195-14213f00-dc7c-11ea-9366-d0cdffbaa279.png)

**Comment by SmallRuralDog** [comment]
多对多建议在回调里自己写保存逻辑
